from __future__ import annotations

import re
from urllib.parse import quote_plus

from yt_dlp import YoutubeDL

from jarvis.log import log

_HINTS = re.compile(r"(?i)\b(official audio|official video|topic)\b")
_REJECT = re.compile(
    r"(?i)\b("
    r"cover|karaoke|nightcore|bootleg|tribute|remix|reaction|reacts?|"
    r"fan\s*made|tutorial|slowed|reverb"
    r")\b"
    r"|\b8d\b"
    r"|\blive (at|from|in|session|performance|concert)\b"
    r"|(\(|\[)live(\)|\])"
    r"|\b\d+\s*hours?\b"
    r"|\bextended intro\b"
)
_LICENSED = ("provided to youtube by", "auto-generated by youtube")
_YDL_OPTS = {
    "format": "bestaudio/best",
    "quiet": True,
    "no_warnings": True,
    "noplaylist": True,
    "skip_download": True,
    "extract_flat": False,
    "socket_timeout": 15,
    "ignoreerrors": True,
}


def studio_query(query: str) -> str:
    text = _HINTS.sub(" ", query or "")
    text = re.sub(r"\s+", " ", text).strip(" -")
    return text or (query or "").strip()


def _who(entry: dict) -> str:
    return " ".join(str(entry.get(key) or "") for key in ("uploader", "channel", "artist"))


def is_topic(entry: dict) -> bool:
    return _who(entry).strip().lower().endswith("- topic")


def is_licensed(entry: dict) -> bool:
    description = str(entry.get("description") or "").lower()
    return any(phrase in description for phrase in _LICENSED)


def _priority(entry: dict) -> int:
    if is_topic(entry):
        return 0
    if is_licensed(entry):
        return 1
    return 2


def _rejected(entry: dict, query: str) -> bool:
    title = str(entry.get("title") or "")
    if not title.strip():
        return True
    ask = query.lower()
    for match in _REJECT.finditer(title):
        if match.group(0).lower() not in ask:
            return True
    duration = entry.get("duration")
    if isinstance(duration, (int, float)):
        if duration < 30:
            return True
        if duration > 15 * 60 and not is_topic(entry):
            return True
    return False


def rank_tracks(entries: list[dict], query: str) -> list[dict]:
    seen: set[str] = set()
    kept: list[tuple[int, int, dict]] = []
    for index, entry in enumerate(entries):
        video_id = str(entry.get("id") or "")
        if video_id and video_id in seen:
            continue
        if video_id:
            seen.add(video_id)
        if _rejected(entry, query):
            continue
        kept.append((_priority(entry), index, entry))
    kept.sort(key=lambda item: (item[0], item[1]))
    return [item[2] for item in kept]


def _entries(info: object) -> list[dict]:
    if not isinstance(info, dict):
        return []
    entries = info.get("entries")
    if entries:
        return [entry for entry in entries if entry]
    if info.get("id"):
        return [info]
    return []


def _watch_page(url: str) -> bool:
    return any(host in url for host in ("youtube.com/watch", "youtu.be/", "music.youtube.com"))


def direct_audio_url(entry: dict) -> str | None:
    url = entry.get("url")
    if isinstance(url, str) and url.startswith("http") and not _watch_page(url):
        return url
    return None


class YouTubeResolver:
    def resolve(self, query: str, offset: int = 1) -> dict[str, str]:
        song = studio_query(query)
        if not song:
            raise RuntimeError("missing song query")
        offset = max(int(offset), 1)
        limit = max(5, offset)
        log(f"searching youtube for {song!r} #{offset}")
        official = self._search(f"ytsearch{limit}:{song} official audio")
        ranked = rank_tracks(official, song)
        topic = [entry for entry in ranked if _priority(entry) == 0]
        licensed = [entry for entry in ranked if _priority(entry) == 1]
        rest = [entry for entry in ranked if _priority(entry) == 2]
        pool = _dedupe(topic + licensed)
        if len(pool) < offset:
            log("trying youtube music")
            pool = _dedupe(pool + rank_tracks(self._search_music(song, limit), song))
        if len(pool) < offset:
            pool = _dedupe(pool + rest)
        if len(pool) < offset:
            raise RuntimeError(f"no official track for {song!r} at offset {offset}")
        chosen = self._hydrate(pool[offset - 1])
        stream = direct_audio_url(chosen)
        if not stream:
            raise RuntimeError(f"no audio stream for {chosen.get('title') or song!r}")
        title = str(chosen.get("title") or song)
        video_id = chosen.get("id")
        page = chosen.get("webpage_url") or chosen.get("original_url")
        if not page and video_id:
            page = f"https://www.youtube.com/watch?v={video_id}"
        if not page:
            raise RuntimeError(f"incomplete metadata for {song!r}")
        return {
            "title": title,
            "webpage_url": str(page),
            "stream_url": stream,
            "video_id": str(video_id or ""),
        }

    def resolve_page(self, page: str) -> dict[str, str]:
        if not page:
            raise RuntimeError("missing saved track")
        log(f"reusing saved track {page}")
        with YoutubeDL(_YDL_OPTS) as ydl:
            info = ydl.extract_info(page, download=False)
        if not isinstance(info, dict):
            raise RuntimeError(f"saved track unavailable: {page}")
        stream = direct_audio_url(info)
        if not stream:
            raise RuntimeError(f"no audio stream for {info.get('title') or page}")
        video_id = info.get("id")
        webpage = info.get("webpage_url") or page
        return {
            "title": str(info.get("title") or page),
            "webpage_url": str(webpage),
            "stream_url": stream,
            "video_id": str(video_id or ""),
        }

    def _search(self, query: str) -> list[dict]:
        with YoutubeDL(_YDL_OPTS) as ydl:
            info = ydl.extract_info(query, download=False)
        return _entries(info)

    def _search_music(self, query: str, limit: int) -> list[dict]:
        url = f"https://music.youtube.com/search?q={quote_plus(query)}"
        opts = {**_YDL_OPTS, "noplaylist": False, "playlistend": limit}
        try:
            with YoutubeDL(opts) as ydl:
                info = ydl.extract_info(url, download=False)
        except Exception as exc:
            log(f"youtube music search failed: {exc}")
            return []
        return _entries(info)[:limit]

    def _hydrate(self, entry: dict) -> dict:
        if direct_audio_url(entry):
            return entry
        video_id = entry.get("id")
        if not video_id:
            return entry
        with YoutubeDL(_YDL_OPTS) as ydl:
            info = ydl.extract_info(
                f"https://www.youtube.com/watch?v={video_id}",
                download=False,
            )
        return info or entry


def _dedupe(entries: list[dict]) -> list[dict]:
    seen: set[str] = set()
    unique: list[dict] = []
    for entry in entries:
        video_id = str(entry.get("id") or id(entry))
        if video_id in seen:
            continue
        seen.add(video_id)
        unique.append(entry)
    return unique
