import os

from dotenv import load_dotenv
import pyaudio

load_dotenv()

FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 16000
OUTPUT_RATE = 24000
CHUNK = 1280

WAKE_MODEL = "hey_jarvis"
WAKE_THRESHOLD = 0.7
WAKE_THRESHOLD_MUSIC = 0.92
WAKE_QUIET = 0.3
WAKE_QUIET_CHUNKS = 10
WAKE_CONFIRM_CHUNKS = 4
WAKE_CONFIRM_CHUNKS_MUSIC = 6
WAKE_COOLDOWN_SECONDS = 6.0
WAKE_PLAYBACK_COOLDOWN_SECONDS = 12.0
WAKE_FALSE_COOLDOWN_SECONDS = 10.0
PCM_MIME = "audio/pcm;rate=16000"

SILENCE_RMS_THRESHOLD = 450.0
SPEECH_CONFIRM_CHUNKS = 3
SILENCE_SECONDS = 1.5
MAX_UTTERANCE_SECONDS = 5.0
RESPONSE_TIMEOUT = 40.0

LIVE_MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.8-live")
GEMINI_VOICE = "Orus"

MPV_IPC_PATH = "/tmp/mpvsocket"
MUSIC_VOLUME_NORMAL = 100
MUSIC_VOLUME_DUCKED = 15
